### ISSUE TITLE
Alexa Week 20 To-Do

### ISSUE THREAD

**Issue by alexac54767** [alexac54767/Alexa-Fastpage#26]
- [x]  MCQ test <- [GOOD REFLECTION](https://alexac54767.github.io/Alexa-Fastpage/collegeboard/MCQ2)
- [x] [blog about role with project](https://alexac54767.github.io/Alexa-Fastpage/project/myrole)
- [x] [5.1 and 5.2 hacks ](https://alexac54767.github.io/Alexa-Fastpage/collegeboard/chapterfive)
